// frontend/src/pages/login/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import { webLogin, webRegister } from '../../services/auth.js'
import { isWeb } from '../../services/platform.js'

const isLoginMode = ref(true)
const email = ref('')
const password = ref('')
const confirmPassword = ref('')
const loading = ref(false)
const errorMsg = ref('')

// Web 平台才显示此页面
if (!isWeb()) {
  uni.switchTab({ url: '/pages/home/index' })
}

function toggleMode() {
  isLoginMode.value = !isLoginMode.value
  errorMsg.value = ''
}

function validate(): boolean {
  if (!email.value.trim()) {
    errorMsg.value = '请输入邮箱'
    return false
  }
  if (!email.value.includes('@')) {
    errorMsg.value = '邮箱格式不正确'
    return false
  }
  if (!password.value || password.value.length < 6) {
    errorMsg.value = '密码至少6位'
    return false
  }
  if (!isLoginMode.value && password.value !== confirmPassword.value) {
    errorMsg.value = '两次密码不一致'
    return false
  }
  errorMsg.value = ''
  return true
}

async function handleSubmit() {
  if (!validate()) return
  loading.value = true

  try {
    if (isLoginMode.value) {
      await webLogin(email.value.trim(), password.value)
    } else {
      await webRegister(email.value.trim(), password.value)
    }
    uni.switchTab({ url: '/pages/home/index' })
  } catch (err: any) {
    errorMsg.value = err.message || '操作失败，请重试'
  } finally {
    loading.value = false
  }
}

function goBack() {
  uni.navigateBack()
}
</script>

<template>
  <view class="page">
    <view class="container">
      <!-- 返回按钮 -->
      <view class="back-btn" @click="goBack">
        <text class="back-arrow">←</text>
        <text class="back-text">返回</text>
      </view>

      <!-- 标题区 -->
      <view class="header">
        <text class="title">{{ isLoginMode ? '欢迎回来' : '创建账户' }}</text>
        <text class="subtitle">
          {{ isLoginMode ? '登录以继续你的书写旅程' : '注册开始记录你的故事' }}
        </text>
      </view>

      <!-- 表单 -->
      <view class="form-card">
        <view class="input-group">
          <text class="input-label">邮箱</text>
          <input
            v-model="email"
            class="input"
            type="text"
            placeholder="your@email.com"
            placeholder-class="input-placeholder"
          />
        </view>

        <view class="input-group">
          <text class="input-label">密码</text>
          <input
            v-model="password"
            class="input"
            type="password"
            placeholder="至少6位"
            placeholder-class="input-placeholder"
          />
        </view>

        <view v-if="!isLoginMode" class="input-group">
          <text class="input-label">确认密码</text>
          <input
            v-model="confirmPassword"
            class="input"
            type="password"
            placeholder="再次输入密码"
            placeholder-class="input-placeholder"
          />
        </view>

        <!-- 错误提示 -->
        <view v-if="errorMsg" class="error-banner">
          <text class="error-text">{{ errorMsg }}</text>
        </view>

        <!-- 提交按钮 -->
        <view
          class="submit-btn"
          :class="{ disabled: loading }"
          @click="handleSubmit"
        >
          <text v-if="!loading" class="submit-text">
            {{ isLoginMode ? '登录' : '注册' }}
          </text>
          <text v-else class="submit-text">处理中...</text>
        </view>
      </view>

      <!-- 切换模式 -->
      <view class="toggle-section">
        <text class="toggle-text">
          {{ isLoginMode ? '还没有账户？' : '已有账户？' }}
        </text>
        <text class="toggle-link" @click="toggleMode">
          {{ isLoginMode ? '立即注册' : '直接登录' }}
        </text>
      </view>

      <!-- 底部提示 -->
      <view class="footer">
        <text class="footer-text">你的隐私对我们很重要，数据将安全存储</text>
      </view>
    </view>
  </view>
</template>

<style scoped>
.page {
  min-height: 100vh;
  background-color: var(--color-bg);
}

.container {
  padding: var(--space-xl);
  max-width: 480px;
  margin: 0 auto;
}

.back-btn {
  display: flex;
  align-items: center;
  gap: var(--space-xs);
  padding: var(--space-md) 0;
  margin-bottom: var(--space-lg);
}

.back-arrow {
  font-size: var(--text-lg);
  color: var(--color-text-secondary);
}

.back-text {
  font-size: var(--text-sm);
  color: var(--color-text-secondary);
}

.header {
  margin-bottom: var(--space-2xl);
}

.title {
  font-size: var(--text-2xl);
  font-family: var(--font-serif);
  color: var(--color-text-primary);
  display: block;
  margin-bottom: var(--space-sm);
}

.subtitle {
  font-size: var(--text-base);
  color: var(--color-text-secondary);
  display: block;
}

.form-card {
  background: var(--color-surface);
  border-radius: var(--radius-lg);
  padding: var(--space-xl);
  box-shadow: var(--shadow-sm);
  margin-bottom: var(--space-xl);
}

.input-group {
  margin-bottom: var(--space-lg);
}

.input-group:last-of-type {
  margin-bottom: var(--space-md);
}

.input-label {
  font-size: var(--text-sm);
  color: var(--color-text-secondary);
  display: block;
  margin-bottom: var(--space-sm);
}

.input {
  width: 100%;
  height: 48px;
  padding: 0 var(--space-md);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  font-size: var(--text-base);
  color: var(--color-text-primary);
  background: var(--color-surface-warm);
  box-sizing: border-box;
}

.input:focus {
  border-color: var(--color-border-focus);
  outline: none;
}

.input-placeholder {
  color: var(--color-text-muted);
}

.error-banner {
  background: var(--color-crisis-light);
  border-radius: var(--radius-sm);
  padding: var(--space-sm) var(--space-md);
  margin-bottom: var(--space-lg);
}

.error-text {
  font-size: var(--text-sm);
  color: var(--color-crisis);
}

.submit-btn {
  width: 100%;
  height: 48px;
  background: var(--color-primary);
  border-radius: var(--radius-md);
  display: flex;
  align-items: center;
  justify-content: center;
  transition: opacity var(--duration-fast);
}

.submit-btn.disabled {
  opacity: 0.6;
}

.submit-text {
  font-size: var(--text-base);
  color: var(--color-text-on-primary);
  font-weight: 500;
}

.toggle-section {
  text-align: center;
  margin-bottom: var(--space-2xl);
}

.toggle-text {
  font-size: var(--text-sm);
  color: var(--color-text-secondary);
}

.toggle-link {
  font-size: var(--text-sm);
  color: var(--color-primary);
  font-weight: 500;
  margin-left: var(--space-xs);
}

.footer {
  text-align: center;
  padding-bottom: var(--space-xl);
}

.footer-text {
  font-size: var(--text-xs);
  color: var(--color-text-muted);
}
</style>

// pc-frontend/src/app/login/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { webLogin, webRegister } from '@/lib/api'

export default function LoginPage() {
  const router = useRouter()
  const [isLoginMode, setIsLoginMode] = useState(true)
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  function validate(): boolean {
    if (!email.trim()) {
      setError('请输入邮箱')
      return false
    }
    if (!email.includes('@')) {
      setError('邮箱格式不正确')
      return false
    }
    if (!password || password.length < 6) {
      setError('密码至少6位')
      return false
    }
    if (!isLoginMode && password !== confirmPassword) {
      setError('两次密码不一致')
      return false
    }
    return true
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!validate()) return

    setError('')
    setLoading(true)

    try {
      if (isLoginMode) {
        await webLogin(email.trim(), password)
      } else {
        await webRegister(email.trim(), password)
      }
      router.push('/')
    } catch (err) {
      setError(err instanceof Error ? err.message : '操作失败，请重试')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-[#F5F0EB] flex items-center justify-center px-6">
      <div className="w-full max-w-md animate-fade-in-up">
        {/* Back Link */}
        <Link
          href="/"
          className="inline-flex items-center gap-1 text-sm text-[#6B6560] hover:text-[#2C2420] transition-colors mb-8"
        >
          <span>←</span>
          <span>返回</span>
        </Link>

        {/* Header */}
        <div className="mb-10">
          <h1
            className="text-3xl text-[#2C2420] mb-2"
            style={{ fontFamily: 'var(--font-serif)' }}
          >
            {isLoginMode ? '欢迎回来' : '创建账户'}
          </h1>
          <p className="text-[#6B6560]">
            {isLoginMode ? '登录以继续你的书写旅程' : '注册开始记录你的故事'}
          </p>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="bg-white rounded-2xl p-8 shadow-[0_1px_4px_rgba(44,36,32,0.05)]">
            {/* Email */}
            <div className="mb-5">
              <label className="block text-sm text-[#6B6560] mb-2">邮箱</label>
              <input
                type="email"
                value={email}
                onChange={(e) => {
                  setEmail(e.target.value)
                  setError('')
                }}
                placeholder="your@email.com"
                className="w-full h-12 px-4 bg-[#FAF6F1] border border-[#EBE7E2] rounded-xl text-[#2C2420] text-base placeholder-[#B5ADA5] focus:border-[#4A6352] transition-colors"
              />
            </div>

            {/* Password */}
            <div className="mb-5">
              <label className="block text-sm text-[#6B6560] mb-2">密码</label>
              <input
                type="password"
                value={password}
                onChange={(e) => {
                  setPassword(e.target.value)
                  setError('')
                }}
                placeholder="至少6位"
                className="w-full h-12 px-4 bg-[#FAF6F1] border border-[#EBE7E2] rounded-xl text-[#2C2420] text-base placeholder-[#B5ADA5] focus:border-[#4A6352] transition-colors"
              />
            </div>

            {/* Confirm Password */}
            {!isLoginMode && (
              <div className="mb-5">
                <label className="block text-sm text-[#6B6560] mb-2">确认密码</label>
                <input
                  type="password"
                  value={confirmPassword}
                  onChange={(e) => {
                    setConfirmPassword(e.target.value)
                    setError('')
                  }}
                  placeholder="再次输入密码"
                  className="w-full h-12 px-4 bg-[#FAF6F1] border border-[#EBE7E2] rounded-xl text-[#2C2420] text-base placeholder-[#B5ADA5] focus:border-[#4A6352] transition-colors"
                />
              </div>
            )}

            {/* Error */}
            {error && (
              <div className="bg-[#FCEAE8] rounded-xl p-3 mb-5">
                <p className="text-sm text-[#C45B4A]">{error}</p>
              </div>
            )}

            {/* Submit */}
            <button
              type="submit"
              disabled={loading}
              className={`w-full h-12 rounded-xl text-white font-medium transition-all duration-150 ${
                loading
                  ? 'bg-[#4A6352]/60 cursor-not-allowed'
                  : 'bg-[#4A6352] hover:bg-[#3A4F40] active:scale-[0.98]'
              }`}
            >
              {loading ? '处理中...' : isLoginMode ? '登录' : '注册'}
            </button>
          </div>
        </form>

        {/* Toggle */}
        <div className="text-center mt-6">
          <span className="text-sm text-[#6B6560]">
            {isLoginMode ? '还没有账户？' : '已有账户？'}
          </span>
          <button
            onClick={() => {
              setIsLoginMode(!isLoginMode)
              setError('')
            }}
            className="text-sm text-[#4A6352] font-medium ml-1 hover:underline"
          >
            {isLoginMode ? '立即注册' : '直接登录'}
          </button>
        </div>

        {/* Footer */}
        <p className="text-center text-xs text-[#B5ADA5] mt-10">
          你的隐私对我们很重要，数据将安全存储
        </p>
      </div>
    </div>
  )
}
